development:
  adapter: mysql2
  database: ig_images
  host: localhost
  username: root
  password: 
  encoding: utf8

production:
  adapter: mysql2
  database: ig_line_bot
  host: aairbpykt0kz5q.cexdumasqbd7.us-west-2.rds.amazonaws.com
  username: Micky40086
  password: hehehehe
  encoding: utf8